### ISSUE TITLE
Show missing php extensions

### ISSUE THREAD

**Issue by borriglione** [magento-hackathon/DevDashboard2#11]

**Comment by schmengler** [comment]
System requirements should be available in `Magento_Setup` module. Idea was to highlight required extensions in green and add missing extensions in red.

**Comment by borriglione** [comment]
https://github.com/magento/magento2/blob/2.2-develop/setup/src/Magento/Setup/Model/PhpReadinessCheck.php

```checkPhpExtensions()``` will be helpful. Source could be:


```
        $required = $this->composerInformation->getRequiredExtensions();
        $current = $this->phpInformation->getCurrent();
        $missing = array_values(array_diff($required, $current));
```
