### ISSUE TITLE
Contribution / Pull request management

### ISSUE THREAD

**Issue by borriglione** [magento-hackathon/DevDashboard2#18]
@schmengler 
@wilfriedwolf 

How to we want to handle future pull requests?
If its submitted by an external author one of us should review it. But what do we do if one of us made a change? :)

**Comment by schmengler** [comment]
Thanks for picking this up again @borriglione ! I find code reviews useful in any case, so as long as we are the three maintainers I suggest to assign PRs to the other two and if there's no review from either one within a week (😇) ping on a different channel

**Comment by borriglione** [comment]
Alright. Lets do so :) Greetings to you!

**Comment by wilfriedwolf** [comment]
I agree. Just starting over Magento2, so might be a good thing to do
code review. If I understand it, it shoud at least be sufficiently clear
;)

-- 
Wilfried Wolf
Softwareentwicklung

Sandstein Neue Medien GmbH
Goetheallee 6 · Eingang Händelallee · 01309 Dresden
Tel. direkt +49 (0)351 44078-32 · Zentrale +49 (0)351 44078-40 · Fax
+49 (0)351 44078-12
wilfried.wolf@sandstein.de · https://www.sandstein.de/internetagentur 
 
Folgen Sie uns per Facebook - Twitter - Instagram: 
www.facebook.com/Sandstein.de
www.twitter.com/sandstein
www.instagram.com/sandstein_neue_medien



>>> schmengler <notifications@github.com> schrieb am Montag, 18. Juni
2018 um 15:02
in Nachricht
<magento-hackathon/DevDashboard2/issues/18/398046237@github.com>:
> Thanks for picking this up again @borriglione ! I find code reviews
useful in 
> any case, so as long as we are the three maintainers I suggest to
assign PRs 
> to the other two and if there's no review from either one within a
week (��)
